package com.sinco.common.area;

import java.util.Currency;
import java.util.List;
import java.util.Map;

import com.google.common.collect.Lists;
import com.google.common.collect.Maps;

public class CountryUtil {

	public static Map<String, Country> map=Maps.newHashMap();

//	public static List<Country> list=Lists.newArrayList(
//			new Country(Continent.Asia,"中国大陆","China","86",Currency.getInstance("CNY")),
//			new Country(Continent.Asia,"香港","Hong Kong","852",Currency.getInstance("HKD")),
//			new Country(Continent.Asia,"澳门","Macao","853",Currency.getInstance("MOP")),
//			new Country(Continent.Asia,"台湾","Taiwan","886",Currency.getInstance("TWD")),
//			new Country(Continent.Asia,"马来西亚","Malaysia Ringgit","60",Currency.getInstance("MYR")),
//			new Country(Continent.Asia,"印度尼西亚","Indonesia","62",Currency.getInstance("IDR")),
//			new Country(Continent.Asia,"菲律宾","The Philippines","63",Currency.getInstance("PHP")),
//			new Country(Continent.Asia,"新加坡","Singapore Dollar","65",Currency.getInstance("SGD")),
//			new Country(Continent.Asia,"泰国","Thailand","66",Currency.getInstance("THB")),
//			new Country(Continent.Asia,"日本","Japan","81",Currency.getInstance("JPY")),
//			new Country(Continent.Asia,"韩国","Republic of Korea","82",Currency.getInstance("KRW")),
//			new Country(Continent.Asia,"塔吉克斯坦","Tajikistan","7",Currency.getInstance("TJS")),
//			new Country(Continent.Asia,"哈萨克斯坦","Kazakhstan","7",Currency.getInstance("KZT")),
//			new Country(Continent.Asia,"越南","Vietnam","84",Currency.getInstance("VND")),
//			new Country(Continent.Asia,"土耳其","Turkey","90",Currency.getInstance("TRY")),
//			new Country(Continent.Asia,"印度","India","91",Currency.getInstance("INR")),
//			new Country(Continent.Asia,"巴基斯坦","Pakistan","92",Currency.getInstance("PKR")),
//			new Country(Continent.Asia,"阿富汗","Afghanistan","93",Currency.getInstance("AFA")),
//			new Country(Continent.Asia,"斯里兰卡","Sri Lanka","94",Currency.getInstance("LKR")),
//			new Country(Continent.Asia,"缅甸","Myanmar","95",Currency.getInstance("BUK")),
//			new Country(Continent.Asia,"伊朗","Iran","98",Currency.getInstance("IRR")),
//			new Country(Continent.Asia,"亚美尼亚","Armenia","374",Currency.getInstance("AMD")),
//			new Country(Continent.Asia,"东帝汶","Timor-Leste","670",Currency.getInstance("USD")),
//			new Country(Continent.Asia,"文莱","Brunei","673",Currency.getInstance("BND")),
//			new Country(Continent.Asia,"朝鲜","Korea","850",Currency.getInstance("KPW")),
//			new Country(Continent.Asia,"柬埔寨","Cambodia","855",Currency.getInstance("KHR")),
//			new Country(Continent.Asia,"老挝","Laos","856",Currency.getInstance("LAK")),
//			new Country(Continent.Asia,"孟加拉国","Laos","880",Currency.getInstance("BDT")),
//			new Country(Continent.Asia,"马尔代夫","Maldives","960",Currency.getInstance("MWK")),
//			new Country(Continent.Asia,"黎巴嫩","Lebanon","961",Currency.getInstance("LBP")),
//			new Country(Continent.Asia,"约旦","Jordan","962",Currency.getInstance("JOD")),
//			new Country(Continent.Asia,"叙利亚","Syria","963",Currency.getInstance("SYP")),
//			new Country(Continent.Asia,"伊拉克","Iraq","964",Currency.getInstance("IQD")),
//			new Country(Continent.Asia,"科威特","Kuwait","965",Currency.getInstance("KWD")),
//			new Country(Continent.Asia,"沙特阿拉伯","Saudi Arabia","966",Currency.getInstance("SAR")),
//			new Country(Continent.Asia,"也门","Yemen","967",Currency.getInstance("YER")),
//			new Country(Continent.Asia,"阿曼","Oman","968",Currency.getInstance("OMR")),
//			new Country(Continent.Asia,"巴勒斯坦","Palestine","970",Currency.getInstance("ILS")),
//			new Country(Continent.Asia,"阿联酋","United Arab Emirates","971",Currency.getInstance("AED")),
//			new Country(Continent.Asia,"以色列","Israel","972",Currency.getInstance("ILS")),
//			new Country(Continent.Asia,"巴林","Bahrain","973",Currency.getInstance("BHD")),
//			new Country(Continent.Asia,"卡塔尔","Qatar","974",Currency.getInstance("QAR")),
//			new Country(Continent.Asia,"不丹","Bhutan","975",Currency.getInstance("BTN")),
//			new Country(Continent.Asia,"蒙古","Mongolia","976",Currency.getInstance("MNT")),
//			new Country(Continent.Asia,"尼泊尔","Nepal","977",Currency.getInstance("NPR")),
//			new Country(Continent.Asia,"土库曼斯坦","Turkmenistan","993",Currency.getInstance("TMT")),
//			new Country(Continent.Asia,"阿塞拜疆","Azerbaijan","994",Currency.getInstance("AZN")),
//			new Country(Continent.Asia,"乔治亚","Georgia","995",Currency.getInstance("GEL")),
//			new Country(Continent.Asia,"吉尔吉斯斯坦","Kyrgyzstan","996",Currency.getInstance("KGS")),
//			new Country(Continent.Asia,"乌兹别克斯坦","Uzbekistan","998",Currency.getInstance("UZS")),
//			new Country(Continent.Europe,"英国","United Kingdom","44",Currency.getInstance("GBP")),
//			new Country(Continent.Europe,"德国","Germany","49",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"意大利","Germany","39",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"法国","France","33",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"俄罗斯","Russia","7",Currency.getInstance("RUB")),
//			new Country(Continent.Europe,"希腊","Greece","30",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"荷兰","Netherlands","31",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"比利时","Belgium","32",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"西班牙","Spain","34",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"匈牙利","Hungary","36",Currency.getInstance("HUF")),
//			new Country(Continent.Europe,"罗马尼亚","Romania","40",Currency.getInstance("RON")),
//			new Country(Continent.Europe,"瑞士","Switzerland","41",Currency.getInstance("CHF")),
//			new Country(Continent.Europe,"奥地利","Austria","43",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"丹麦","Denmark","45",Currency.getInstance("DKK")),
//			new Country(Continent.Europe,"瑞典","Sweden","46",Currency.getInstance("SEK")),
//			new Country(Continent.Europe,"挪威","Norway","47",Currency.getInstance("NOK")),
//			new Country(Continent.Europe,"波兰","Poland","48",Currency.getInstance("PLN")),
//			new Country(Continent.Europe,"圣马力诺","San Marino","223",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"直布罗陀","Gibraltar","350",Currency.getInstance("GBP")),
//			new Country(Continent.Europe,"葡萄牙","Portugal","351",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"卢森堡","Luxembourg","352",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"爱尔兰","Ireland","353",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"冰岛","Iceland","354",Currency.getInstance("ISK")),
//			new Country(Continent.Europe,"阿尔巴尼亚","Albania","355",Currency.getInstance("ALL")),
//			new Country(Continent.Europe,"马耳他","Malta","356",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"塞浦路斯","Cyprus","357",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"芬兰","Finland","358",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"保加利亚","Bulgaria","359",Currency.getInstance("BGN")),
//			new Country(Continent.Europe,"立陶宛","Lithuania","370",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"拉脱维亚","Latvia","371",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"爱沙尼亚","Estonia","372",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"摩尔多瓦","Moldova","373",Currency.getInstance("MDL")),
//			new Country(Continent.Europe,"安道尔共和国","Andorra","376",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"乌克兰","Ukraine","380",Currency.getInstance("UAH")),
//			new Country(Continent.Europe,"克罗地亚","Croatia","385",Currency.getInstance("HRK")),
//			new Country(Continent.Europe,"斯洛文尼亚","Slovenia","386",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"波黑","Bosnia","387",Currency.getInstance("BAM")),
//			new Country(Continent.Europe,"马其顿","Macedonia","389",Currency.getInstance("MKD")),
//			new Country(Continent.Europe,"梵蒂冈","Vatican","396",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"捷克","Czech","420",Currency.getInstance("CZK")),
//			new Country(Continent.Europe,"斯洛伐克","Slovakia","421",Currency.getInstance("EUR")),
//			new Country(Continent.Europe,"列支敦士登","Liechtenstein","423",Currency.getInstance("CHF")),
//			new Country(Continent.South_America,"秘鲁","Peru","51",Currency.getInstance("PEN")),
//			new Country(Continent.South_America,"墨西哥","Mexico","52",Currency.getInstance("MXN")),
//			new Country(Continent.South_America,"古巴","Cuba","53",Currency.getInstance("CUP")),
//			new Country(Continent.South_America,"阿根廷","Argentina","54",Currency.getInstance("ARS")),
//			new Country(Continent.South_America,"巴西","Brazil","55",Currency.getInstance("BRL")),
//			new Country(Continent.South_America,"智利","Chile","56",Currency.getInstance("CLP")),
//			new Country(Continent.South_America,"哥伦比亚","Columbia","57",Currency.getInstance("COP")),
//			new Country(Continent.South_America,"委内瑞拉","Venezuela","58",Currency.getInstance("VEF")),
//			new Country(Continent.South_America,"福克兰群岛","Falkland Islands","500",Currency.getInstance("FKP")),
//			new Country(Continent.South_America,"伯利兹","Belize","501",Currency.getInstance("BZD")),
//			new Country(Continent.South_America,"危地马拉","Guatemala","502",Currency.getInstance("GTQ")),
//			new Country(Continent.South_America,"萨尔瓦多","El Salvador","503",Currency.getInstance("SVC")),
//			new Country(Continent.South_America,"洪都拉斯","Honduras","504",Currency.getInstance("HNL")),
//			new Country(Continent.South_America,"尼加拉瓜","Nicaragua","505",Currency.getInstance("NIO")),
//			new Country(Continent.South_America,"哥斯达黎加","Costa Rica","506",Currency.getInstance("CRC")),
//			new Country(Continent.South_America,"巴拿马","Panama","507",Currency.getInstance("PAB")),
//			new Country(Continent.South_America,"圣彼埃尔","Saint Pierre","508",Currency.getInstance("EUR")),
//			new Country(Continent.South_America,"海地","Saint Pierre","509",Currency.getInstance("HTG")),
//			new Country(Continent.South_America,"瓜德罗普","Guadeloupe","590",Currency.getInstance("EUR")),
//			new Country(Continent.South_America,"玻利维亚","Bolivia","591",Currency.getInstance("BOB")),
//			new Country(Continent.South_America,"圭亚那","Guyana","592",Currency.getInstance("GYD")),
//			new Country(Continent.South_America,"厄瓜多尔","Ecuador","593",Currency.getInstance("ECS")),
//			new Country(Continent.South_America,"巴拉圭","Paraguay","595",Currency.getInstance("PYG")),
//			new Country(Continent.South_America,"马提尼克","Martinique","596",Currency.getInstance("EUR")),
//			new Country(Continent.South_America,"苏里南","Suriname","597",Currency.getInstance("SRD")),
//			new Country(Continent.South_America,"乌拉圭","Uruguay","598",Currency.getInstance("UYU")),
//			new Country(Continent.Africa,"埃及","Egypt","20",Currency.getInstance("EGP")),
//			new Country(Continent.Africa,"南非","South Africa","27",Currency.getInstance("ZAR")),
//			new Country(Continent.Africa,"摩洛哥","Morocco","212",Currency.getInstance("MAD")),
//			new Country(Continent.Africa,"阿尔及利亚","Algeria","213",Currency.getInstance("DZD")),
//			new Country(Continent.Africa,"突尼斯","Tunisia","216",Currency.getInstance("TND")),
//			new Country(Continent.Africa,"利比亚","Libya","218",Currency.getInstance("LYD")),
//			new Country(Continent.Africa,"冈比亚","Gambia","220",Currency.getInstance("GMD")),
//			new Country(Continent.Africa,"塞内加尔","Senegal","221",Currency.getInstance("XOF")),
//			new Country(Continent.Africa,"毛里塔尼亚","Mauritania","222",Currency.getInstance("MRO")),
//			new Country(Continent.Africa,"马里","Mali","223",Currency.getInstance("XOF")),
//			new Country(Continent.Africa,"几内亚","Guinea","224",Currency.getInstance("GNF")),
//			new Country(Continent.Africa,"科特迪瓦","Cote d'Ivoire","225",Currency.getInstance("XOF")),
//			new Country(Continent.Africa,"布基纳法索","Burkina Faso","226",Currency.getInstance("XOF")),
//			new Country(Continent.Africa,"尼日尔","Niger","227",Currency.getInstance("XOF")),
//			new Country(Continent.Africa,"多哥","Togo","228",Currency.getInstance("XOF")),
//			new Country(Continent.Africa,"贝宁","Benin","229",Currency.getInstance("XOF")),
//			new Country(Continent.Africa,"毛里求斯","Mauritius","230",Currency.getInstance("MUR")),
//			new Country(Continent.Africa,"利比里亚","Liberia","231",Currency.getInstance("LRD")),
//			new Country(Continent.Africa,"塞拉利昂","Sierra Leone","232",Currency.getInstance("SLL")),
//			new Country(Continent.Africa,"加纳","Ghana","233",Currency.getInstance("GHS")),
//			new Country(Continent.Africa,"尼日利亚","Nigeria","234",Currency.getInstance("NGN")),
//			new Country(Continent.Africa,"乍得","Chad","235",Currency.getInstance("XAF")),
//			new Country(Continent.Africa,"中非","Central African","236",Currency.getInstance("XAF")),
//			new Country(Continent.Africa,"喀麦隆","Cameroon","237",Currency.getInstance("XAF")),
//			new Country(Continent.Africa,"佛得角","Cape Verde","238",Currency.getInstance("CVE")),
//			new Country(Continent.Africa,"圣多美","Sao Tome","239",Currency.getInstance("STD")),
//			new Country(Continent.Africa,"普林西比","Principe","239",Currency.getInstance("STD")),
//			new Country(Continent.Africa,"赤道几内亚","Equatorial Guinea","240",Currency.getInstance("XAF")),
//			new Country(Continent.Africa,"加蓬","Gabon","241",Currency.getInstance("XAF")),
//			new Country(Continent.Africa,"刚果","Congo","242",Currency.getInstance("XAF")),
//			new Country(Continent.Africa,"扎伊尔","Zaire","243",Currency.getInstance("CDF")),
//			new Country(Continent.Africa,"安哥拉","Angola","244",Currency.getInstance("AOA")),
//			new Country(Continent.Africa,"几内亚比绍","Guinea-Bissau","245",Currency.getInstance("XAF")),
//			new Country(Continent.Africa,"阿森松","Ascension","247",Currency.getInstance("GBP")),
//			new Country(Continent.Africa,"塞舌尔","Seychelles","248",Currency.getInstance("SCR")),
//			new Country(Continent.Africa,"苏丹","Sultan","249",Currency.getInstance("SDG")),
//			new Country(Continent.Africa,"卢旺达","Rwanda","250",Currency.getInstance("RWF")),
//			new Country(Continent.Africa,"埃塞俄比亚","Ethiopia","251",Currency.getInstance("ETB")),
//			new Country(Continent.Africa,"索马里","Somalia","252",Currency.getInstance("SOS")),
//			new Country(Continent.Africa,"吉布提","Djibouti","253",Currency.getInstance("DJF")),
//			new Country(Continent.Africa,"肯尼亚","Kenya","254",Currency.getInstance("KES")),
//			new Country(Continent.Africa,"坦桑尼亚","Kenya","255",Currency.getInstance("TZS")),
//			new Country(Continent.Africa,"乌干达","Uganda","256",Currency.getInstance("UGX")),
//			new Country(Continent.Africa,"布隆迪","Burundi","257",Currency.getInstance("BIF")),
//			new Country(Continent.Africa,"莫桑比克","Mozambique","258",Currency.getInstance("MZN")),
//			new Country(Continent.Africa,"赞比亚","Zambia","260",Currency.getInstance("ZMW")),
//			new Country(Continent.Africa,"马达加斯加","Madagascar","261",Currency.getInstance("MGA")),
//			new Country(Continent.Africa,"留尼旺岛","Reunion","262",Currency.getInstance("EUR")),
//			new Country(Continent.Africa,"津巴布韦","Zimbabwe","263",Currency.getInstance("USD")),
//			new Country(Continent.Africa,"纳米比亚","Namibia","264",Currency.getInstance("NAD")),
//			new Country(Continent.Africa,"马拉维","Malawi","265",Currency.getInstance("MWK")),
//			new Country(Continent.Africa,"莱索托","Lesotho","266",Currency.getInstance("LSL")),
//			new Country(Continent.Africa,"博茨瓦纳","Botswana","267",Currency.getInstance("BWP")),
//			new Country(Continent.Africa,"斯威士兰","Swaziland","268",Currency.getInstance("SZL")),
//			new Country(Continent.Africa,"科摩罗","Comoros","269",Currency.getInstance("KMF")),
//			new Country(Continent.Africa,"圣赫勒拿","St. Helena","290",Currency.getInstance("SHP")),
//			new Country(Continent.Africa,"厄立特里亚","Eritrea","291",Currency.getInstance("ERN")),
//			new Country(Continent.Africa,"阿鲁巴岛","Aruba Island","297",Currency.getInstance("AWG")),
//			new Country(Continent.Africa,"法罗群岛","Faroe Islands","298",Currency.getInstance("DKK")),
//			new Country(Continent.Africa,"摩纳哥","Monaco","377",Currency.getInstance("EUR")),
//			new Country(Continent.Oceania,"澳大利亚","Australia","61",Currency.getInstance("AUD")),
//			new Country(Continent.Oceania,"新西兰","New Zealand","64",Currency.getInstance("NZD")),
//			new Country(Continent.Oceania,"关岛","Guam","671",Currency.getInstance("USD")),
//			new Country(Continent.Oceania,"瑙鲁","Nauru","674",Currency.getInstance("AUD")),
//			new Country(Continent.Oceania,"汤加","Tonga","676",Currency.getInstance("TOP")),
//			new Country(Continent.Oceania,"所罗门群岛","Solomon Islands","677",Currency.getInstance("SBD")),
//			new Country(Continent.Oceania,"瓦努阿图","Vanuatu","678",Currency.getInstance("VUV")),
//			new Country(Continent.Oceania,"斐济","Fiji","679",Currency.getInstance("FJD")),
//			new Country(Continent.Oceania,"科克群岛","Cook Islands","682",Currency.getInstance("NZD")),
//			new Country(Continent.Oceania,"纽埃岛","Niue Island","683",Currency.getInstance("NZD")),
//			new Country(Continent.Oceania,"东萨摩亚","Eastern Samoa","684",Currency.getInstance("WST")),
//			new Country(Continent.Oceania,"西萨摩亚","Western Samoa","685",Currency.getInstance("WST")),
//			new Country(Continent.Oceania,"基里巴斯","Kiribati","686",Currency.getInstance("USD")),
//			new Country(Continent.Oceania,"图瓦卢","Tuvalu","688",Currency.getInstance("AUD")),
//			new Country(Continent.Oceania,"科科斯岛","Cocos Islands","619162",Currency.getInstance("AUD")),
//			new Country(Continent.Oceania,"诺福克岛","Norfolk Island","6723",Currency.getInstance("AUD")),
//			new Country(Continent.Oceania,"圣诞岛","Christmas Island","619164",Currency.getInstance("AUD")),
//			new Country(Continent.North_America,"美国","United States","1",Currency.getInstance("USD")),
//			new Country(Continent.North_America,"加拿大","Canada","1",Currency.getInstance("USD")),
//			new Country(Continent.North_America,"夏威夷","Hawaii","1808",Currency.getInstance("USD")),
//			new Country(Continent.North_America,"阿拉斯加","Alaska","1907",Currency.getInstance("USD")),
//			new Country(Continent.North_America,"格陵兰岛","Greenland","299",Currency.getInstance("DKK")),
//			new Country(Continent.North_America,"中途岛","Midway Islands","1808",Currency.getInstance("USD")),
//			new Country(Continent.North_America,"威克岛","Wake Island","1808",Currency.getInstance("USD")),
//			new Country(Continent.North_America,"维尔京群岛","Virgin Islands","1809",Currency.getInstance("USD")),
//			new Country(Continent.North_America,"波多黎各","Puerto Rico","1809",Currency.getInstance("USD")),
//			new Country(Continent.North_America,"巴哈马","Bahamas","1809",Currency.getInstance("BSD")),
//			new Country(Continent.North_America,"安圭拉岛","Anguilla Island","1809",Currency.getInstance("GBP")),
//			new Country(Continent.North_America,"圣卢西亚","Saint Lucia","1809",Currency.getInstance("XCD")),
//			new Country(Continent.North_America,"巴巴多斯","Barbados","1809",Currency.getInstance("BBD")),
//			new Country(Continent.North_America,"牙买加","Jamaica","1876",Currency.getInstance("JMD")),
//			new Country(Continent.Antarctica,"南极洲","64672")
//		);	
	
	public static List<Country> list=Lists.newArrayList(
		new Country(Continent.Asia,"中国大陆","China","86",Currency.getInstance("CNY"),"zh"),
		new Country(Continent.Asia,"香港","852"),
		new Country(Continent.Asia,"澳门","853"),
		new Country(Continent.Asia,"台湾","Taiwan","886",Currency.getInstance("TWD"),"zh"),
		new Country(Continent.Asia,"马来西亚","Malaysia","60",Currency.getInstance("MYR"),"en"),
		new Country(Continent.Asia,"印度尼西亚","62"),
		new Country(Continent.Asia,"菲律宾","63"),
		new Country(Continent.Asia,"新加坡","Singapore","65",Currency.getInstance("SGD"),"en"),
		new Country(Continent.Asia,"泰国","66"),
		new Country(Continent.Asia,"日本","81"),
		new Country(Continent.Asia,"韩国","82"),
		new Country(Continent.Asia,"塔吉克斯坦","7"),
		new Country(Continent.Asia,"哈萨克斯坦","7"),
		new Country(Continent.Asia,"越南","Vietnam","84",Currency.getInstance("VND"),"en"),
		new Country(Continent.Asia,"土耳其","Turkey","90",Currency.getInstance("TRY"),"Turkic"),
		new Country(Continent.Asia,"印度","India","91",Currency.getInstance("INR"),"en"),
		new Country(Continent.Asia,"巴基斯坦","92"),
		new Country(Continent.Asia,"阿富汗","93"),
		new Country(Continent.Asia,"斯里兰卡","94"),
		new Country(Continent.Asia,"缅甸","95"),
		new Country(Continent.Asia,"伊朗","98"),
		new Country(Continent.Asia,"亚美尼亚","374"),
		new Country(Continent.Asia,"东帝汶","670"),
		new Country(Continent.Asia,"文莱","673"),
		new Country(Continent.Asia,"朝鲜","850"),
		new Country(Continent.Asia,"柬埔寨","855"),
		new Country(Continent.Asia,"老挝","856"),
		new Country(Continent.Asia,"孟加拉国","880"),
		new Country(Continent.Asia,"马尔代夫","960"),
		new Country(Continent.Asia,"黎巴嫩","961"),
		new Country(Continent.Asia,"约旦","962"),
		new Country(Continent.Asia,"叙利亚","963"),
		new Country(Continent.Asia,"伊拉克","964"),
		new Country(Continent.Asia,"科威特","965"),
		new Country(Continent.Asia,"沙特阿拉伯","966"),
		new Country(Continent.Asia,"也门","967"),
		new Country(Continent.Asia,"阿曼","968"),
		new Country(Continent.Asia,"巴勒斯坦","970"),
		new Country(Continent.Asia,"阿联酋","971"),
		new Country(Continent.Asia,"以色列","972"),
		new Country(Continent.Asia,"巴林","973"),
		new Country(Continent.Asia,"卡塔尔","974"),
		new Country(Continent.Asia,"不丹","975"),
		new Country(Continent.Asia,"蒙古","976"),
		new Country(Continent.Asia,"尼泊尔","977"),
		new Country(Continent.Asia,"土库曼斯坦","993"),
		new Country(Continent.Asia,"阿塞拜疆","994"),
		new Country(Continent.Asia,"乔治亚","995"),
		new Country(Continent.Asia,"吉尔吉斯斯坦","996"),
		new Country(Continent.Asia,"乌兹别克斯坦","998"),
		new Country(Continent.Europe,"英国","44"),
		new Country(Continent.Europe,"德国","49"),
		new Country(Continent.Europe,"意大利","39"),
		new Country(Continent.Europe,"法国","33"),
		new Country(Continent.Europe,"俄罗斯","Russia","7",Currency.getInstance("RUB"),"ru"),
		new Country(Continent.Europe,"希腊","30"),
		new Country(Continent.Europe,"荷兰","31"),
		new Country(Continent.Europe,"比利时","32"),
		new Country(Continent.Europe,"西班牙","34"),
		new Country(Continent.Europe,"匈牙利","36"),
		new Country(Continent.Europe,"罗马尼亚","40"),
		new Country(Continent.Europe,"瑞士","41"),
		new Country(Continent.Europe,"奥地利","43"),
		new Country(Continent.Europe,"丹麦","45"),
		new Country(Continent.Europe,"瑞典","46"),
		new Country(Continent.Europe,"挪威","47"),
		new Country(Continent.Europe,"波兰","48"),
		new Country(Continent.Europe,"圣马力诺","223"),
		new Country(Continent.Europe,"匈牙利","336"),
		new Country(Continent.Europe,"南斯拉夫","338"),
		new Country(Continent.Europe,"直布罗陀","350"),
		new Country(Continent.Europe,"葡萄牙","351"),
		new Country(Continent.Europe,"卢森堡","352"),
		new Country(Continent.Europe,"爱尔兰","353"),
		new Country(Continent.Europe,"冰岛","354"),
		new Country(Continent.Europe,"阿尔巴尼亚","355"),
		new Country(Continent.Europe,"马耳他","356"),
		new Country(Continent.Europe,"塞浦路斯","357"),
		new Country(Continent.Europe,"芬兰","358"),
		new Country(Continent.Europe,"保加利亚","359"),
		new Country(Continent.Europe,"立陶宛","370"),
		new Country(Continent.Europe,"拉脱维亚","371"),
		new Country(Continent.Europe,"爱沙尼亚","372"),
		new Country(Continent.Europe,"摩尔多瓦","373"),
		new Country(Continent.Europe,"安道尔共和国","376"),
		new Country(Continent.Europe,"乌克兰","Ukraine","380",Currency.getInstance("UAH"),"Ukrainian"),
		new Country(Continent.Europe,"南斯拉夫","381"),
		new Country(Continent.Europe,"克罗地亚","385"),
		new Country(Continent.Europe,"斯洛文尼亚","386"),
		new Country(Continent.Europe,"波黑","387"),
		new Country(Continent.Europe,"马其顿","389"),
		new Country(Continent.Europe,"梵蒂冈","396"),
		new Country(Continent.Europe,"捷克","420"),
		new Country(Continent.Europe,"斯洛伐克","421"),
		new Country(Continent.Europe,"列支敦士登","423"),
		new Country(Continent.South_America,"秘鲁","51"),
		new Country(Continent.South_America,"墨西哥","52"),
		new Country(Continent.South_America,"古巴","53"),
		new Country(Continent.South_America,"阿根廷","54"),
		new Country(Continent.South_America,"巴西","55"),
		new Country(Continent.South_America,"智利","56"),
		new Country(Continent.South_America,"哥伦比亚","57"),
		new Country(Continent.South_America,"委内瑞拉","58"),
		new Country(Continent.South_America,"福克兰群岛","500"),
		new Country(Continent.South_America,"伯利兹","501"),
		new Country(Continent.South_America,"危地马拉","502"),
		new Country(Continent.South_America,"萨尔瓦多","503"),
		new Country(Continent.South_America,"洪都拉斯","504"),
		new Country(Continent.South_America,"尼加拉瓜","505"),
		new Country(Continent.South_America,"哥斯达黎加","506"),
		new Country(Continent.South_America,"巴拿马","507"),
		new Country(Continent.South_America,"圣彼埃尔","508"),
		new Country(Continent.South_America,"海地","509"),
		new Country(Continent.South_America,"瓜德罗普","590"),
		new Country(Continent.South_America,"玻利维亚","591"),
		new Country(Continent.South_America,"圭亚那","592"),
		new Country(Continent.South_America,"厄瓜多尔","593"),
		new Country(Continent.South_America,"法属圭亚那","594"),
		new Country(Continent.South_America,"巴拉圭","595"),
		new Country(Continent.South_America,"马提尼克","596"),
		new Country(Continent.South_America,"苏里南","597"),
		new Country(Continent.South_America,"乌拉圭","598"),
		new Country(Continent.Africa,"埃及","20"),
		new Country(Continent.Africa,"南非","South Africa","27",Currency.getInstance("ZAR"),"en"),
		new Country(Continent.Africa,"摩洛哥","212"),
		new Country(Continent.Africa,"阿尔及利亚","213"),
		new Country(Continent.Africa,"突尼斯","216"),
		new Country(Continent.Africa,"利比亚","218"),
		new Country(Continent.Africa,"冈比亚","220"),
		new Country(Continent.Africa,"塞内加尔","221"),
		new Country(Continent.Africa,"毛里塔尼亚","222"),
		new Country(Continent.Africa,"马里","223"),
		new Country(Continent.Africa,"几内亚","224"),
		new Country(Continent.Africa,"科特迪瓦","225"),
		new Country(Continent.Africa,"布基拉法索","226"),
		new Country(Continent.Africa,"尼日尔","227"),
		new Country(Continent.Africa,"多哥","228"),
		new Country(Continent.Africa,"贝宁","229"),
		new Country(Continent.Africa,"毛里求斯","230"),
		new Country(Continent.Africa,"利比里亚","231"),
		new Country(Continent.Africa,"塞拉利昂","232"),
		new Country(Continent.Africa,"加纳","233"),
		new Country(Continent.Africa,"尼日利亚","234"),
		new Country(Continent.Africa,"乍得","235"),
		new Country(Continent.Africa,"中非","236"),
		new Country(Continent.Africa,"喀麦隆","237"),
		new Country(Continent.Africa,"佛得角","238"),
		new Country(Continent.Africa,"圣多美","239"),
		new Country(Continent.Africa,"普林西比","239"),
		new Country(Continent.Africa,"赤道几内亚","240"),
		new Country(Continent.Africa,"加蓬","241"),
		new Country(Continent.Africa,"刚果","242"),
		new Country(Continent.Africa,"扎伊尔","243"),
		new Country(Continent.Africa,"安哥拉","244"),
		new Country(Continent.Africa,"几内亚比绍","245"),
		new Country(Continent.Africa,"阿森松","247"),
		new Country(Continent.Africa,"塞舌尔","248"),
		new Country(Continent.Africa,"苏丹","249"),
		new Country(Continent.Africa,"卢旺达","250"),
		new Country(Continent.Africa,"埃塞俄比亚","251"),
		new Country(Continent.Africa,"索马里","252"),
		new Country(Continent.Africa,"吉布提","253"),
		new Country(Continent.Africa,"肯尼亚","254"),
		new Country(Continent.Africa,"坦桑尼亚","255"),
		new Country(Continent.Africa,"乌干达","256"),
		new Country(Continent.Africa,"布隆迪","257"),
		new Country(Continent.Africa,"莫桑比克","258"),
		new Country(Continent.Africa,"赞比亚","260"),
		new Country(Continent.Africa,"马达加斯加","261"),
		new Country(Continent.Africa,"留尼旺岛","262"),
		new Country(Continent.Africa,"津巴布韦","263"),
		new Country(Continent.Africa,"纳米比亚","264"),
		new Country(Continent.Africa,"马拉维","265"),
		new Country(Continent.Africa,"莱索托","266"),
		new Country(Continent.Africa,"博茨瓦纳","267"),
		new Country(Continent.Africa,"斯威士兰","268"),
		new Country(Continent.Africa,"科摩罗","269"),
		new Country(Continent.Africa,"圣赫勒拿","290"),
		new Country(Continent.Africa,"厄立特里亚","291"),
		new Country(Continent.Africa,"阿鲁巴岛","297"),
		new Country(Continent.Africa,"法罗群岛","298"),
		new Country(Continent.Africa,"摩纳哥","377"),
		new Country(Continent.Oceania,"澳大利亚","61"),
		new Country(Continent.Oceania,"新西兰","64"),
		new Country(Continent.Oceania,"关岛","671"),
		new Country(Continent.Oceania,"瑙鲁","674"),
		new Country(Continent.Oceania,"汤加","676"),
		new Country(Continent.Oceania,"所罗门群岛","677"),
		new Country(Continent.Oceania,"瓦努阿图","678"),
		new Country(Continent.Oceania,"斐济","679"),
		new Country(Continent.Oceania,"科克群岛","682"),
		new Country(Continent.Oceania,"纽埃岛","683"),
		new Country(Continent.Oceania,"东萨摩亚","684"),
		new Country(Continent.Oceania,"西萨摩亚","685"),
		new Country(Continent.Oceania,"基里巴斯","686"),
		new Country(Continent.Oceania,"图瓦卢","688"),
		new Country(Continent.Oceania,"科科斯岛","619162"),
		new Country(Continent.Oceania,"诺福克岛","6723"),
		new Country(Continent.Oceania,"圣诞岛","619164"),
		new Country(Continent.North_America,"美国","United States","1",Currency.getInstance("USD"),"en"),
		new Country(Continent.North_America,"加拿大","Canada","1",Currency.getInstance("USD"),"en"),
		new Country(Continent.North_America,"夏威夷","1808"),
		new Country(Continent.North_America,"阿拉斯加","1907"),
		new Country(Continent.North_America,"格陵兰岛","299"),
		new Country(Continent.North_America,"中途岛","1808"),
		new Country(Continent.North_America,"威克岛","1808"),
		new Country(Continent.North_America,"维尔京群岛","1809"),
		new Country(Continent.North_America,"波多黎各","1809"),
		new Country(Continent.North_America,"巴哈马","1809"),
		new Country(Continent.North_America,"安圭拉岛","1809"),
		new Country(Continent.North_America,"圣卢西亚","1809"),
		new Country(Continent.North_America,"巴巴多斯","1809"),
		new Country(Continent.North_America,"牙买加","1876"),
		new Country(Continent.Antarctica,"南极洲","64672")
	);
	
	static{
		for (Country country : list) {
			map.put(country.getCode(), country);
		}
	}
	
	/**
	 * 得到国家对象
	 * @param code
	 * @return
	 */
	public static Country get(String code){
		return map.get(code);
	}
	
	/**
	 * 验证是否存在
	 * @param code
	 * @return
	 */
	public static boolean validate(String code){
		return map.containsKey(code);
	}
}
